name: Build Server

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - Server/**
      - .github/workflows/build-server.yml

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
      - name: Navigate to Workspace
        run: cd ${{ github.workspace }}
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore BetterBeatSaber.sln
      - name: Build
        run: dotnet build -c Release Server/Server.csproj